---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 727436185065267200-IDsGfF96cygMe0Y1lzcAj4AxvEmnqEt
:access_token_secret: sL5VxSdW6TIlX9MIS7Na8VIGiH5cUljGWH10aTFBdJaxl
